const INSTRUCTION_TYPE = {
    PRINT:          'INSTR_PRINT',
    DECLARATION:    'INSTR_DECLARATION',
    ASSIGNMENT:     'INSTR_ASSIGNMENT',
    DEC_METHOD:     'INSTR_DEC_METHOD',
    MAIN:           'INSTR_MAIN',
    IF:             'INSTR_IF',
    IF_ELSE:        'INSTR_ELSE',
    ELSE_IF:        'INSTR_ELSE_IF',
    IF_ELSE_IF:     'INSTR_IF_ELSE_IF',
    SWITCH:         'INSTR_SWITCH',
    CASE:           'INSTR_CASE',
    DEFAULT:        'INSTR_DEFAULT',
    WHILE:          'INSTR_WHILE',
    FOR:            'INSTR_FOR',
    DO_WHILE:       'INSTR_DO_WHILE',
    INC:            'INSTR_INC',
    DEC:            'INSTR_DEC',
    DEC_FUNC:       'INSTR_DEC_FUNC',
    CALL:           'INSTR_CALL',
    BREAK:          'INSTR_BREAK',
    CONTINUE:       'INSTR_CONTINUE',
    RETURN:         'INSTR_RETURN',
};

module.exports = INSTRUCTION_TYPE;