const INSTRUCTION_TYPE = {
    PRINT:          'INSTR_PRINT',
    DECLARATION:    'INSTR_DECLARATION',
    ASSIGNMENT:     'INSTR_ASSIGNMENT',
    DEC_METHOD:     'INSTR_DEC_METHOD',
    MAIN:           'INSTR_MAIN',
    IF:             'INSTR_IF',
    IF_ELSE:        'INSTR_ELSE',
    ELSE_IF:        'INSTR_ELSE_IF',
    IF_ELSE_IF:     'INSTR_IF_ELSE_IF',
    SWITCH:         'INSTR_SWITCH',
    CASE:           'INSTR_CASE',
    DEFAULT:        'INSTR_DEFAULT',
    WHILE:          'INSTR_WHILE',
    FOR:            'INSTR_FOR',
    DO_WHILE:       'INSTR_DO_WHILE',
    INC:            'INSTR_INC',
    DEC:            'INSTR_DEC',
    DEC_FUNC:       'INSTR_DEC_FUNC',
    CALL:           'INSTR_CALL',
    BREAK:          'INSTR_BREAK',
    CONTINUE:       'INSTR_CONTINUE',
    RETURN:         'INSTR_RETURN',
    VECTOR_NULL:    'INSTR_VECTOR_NULL',
    VECTOR_VALUES:  'INSTR_VECTOR_VALUES',
    VECTOR_ACCESS:  'INSTR_VECTOR_ACCESS',
    SET_VECTOR:     'INSTR_SET_VECTOR',
    DEC_LIST:       'INSTR_DEC_LIST',
    LIST_VALUES:    'INSTR_LIST_VALUES',
    ADD_LIST:       'INSTR_ADD_LIST',
    LIST_ACCESS:    'INSTR_LIST_ACCESS',
    SET_LIST:       'INSTR_SET_LIST',
};

module.exports = INSTRUCTION_TYPE;